spring:
  application:
    name: devsu-challenge-account
  datasource:
    url: jdbc:mysql://devsu-database:3306/devsu_challenge
    username: root
    password: devsu-database
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

application:
  customer:
    url: http://devsu-user:8080/api/v1/clientes

server:
  port: 8090
